# Dockerfile.fastapi
FROM python:3.10-slim

WORKDIR /opt/fastapi

# 시스템 패키지 설치 (필요 시)
RUN apt-get update && apt-get install -y build-essential curl

# requirements 설치
COPY requirements.txt /opt/fastapi/
RUN pip install --no-cache-dir -r requirements.txt

# FastAPI 소스 복사
COPY invest /opt/fastapi/invest

EXPOSE 8001

CMD ["uvicorn", "invest.main_api:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]