services:

  # MLflow 전용 PostgreSQL
  postgres-mlflow:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: mlflowuser
      POSTGRES_PASSWORD: mlflowpassword
      POSTGRES_DB: mlflowdatabase
    volumes:
      - mlflow_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mlflowuser -d mlflowdatabase"]
      interval: 10s
      timeout: 5s
      retries: 5


  # MLflow 서버 (aws S3 사용)
  mlflow-server:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    restart: always
    depends_on:
      postgres-mlflow:
        condition: service_healthy
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-ap-northeast-2}
    ports:
      - "5001:5000"
    command: >
      mlflow server
      --backend-store-uri postgresql://mlflowuser:mlflowpassword@postgres-mlflow:5432/mlflowdatabase
      --default-artifact-root s3://team2-mlflow-bucket/artifacts/
      --host 0.0.0.0
      --port 5000

volumes:
  mlflow_pg_data: