services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8002:8002"
    env_file:
      - .env             # 필요 없으면 생략
    volumes:
      - ./invest:/opt/fastapi/invest   # 개발 중이면 바인드 마운트
    command: >
      uvicorn invest.main_api:app --host 0.0.0.0 --port 8002 --reload