services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - pg_data:/var/lib/postgresql/data

  airflow-webserver:
    build: .
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - AIRFLOW__WEBSERVER__WEB_SERVER_HOST = 0.0.0.0
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./scenario_app:/opt/airflow/scenario_app
      - ./news_json_files:/opt/airflow/news_json_files
      - ./result_json_files:/opt/airflow/result_json_files
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    build: .
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./scenario_app:/opt/airflow/scenario_app
      - ./news_json_files:/opt/airflow/news_json_files
      - ./result_json_files:/opt/airflow/result_json_files
    command: scheduler

volumes:
  pg_data: