name: Deploy to EC2

on:
  push:
    branches: [ main ]   # 메인 브랜치에 push될 때마다 실행

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (코드 체크아웃)
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            cd /home/ubuntu/default-scenario-generator
            rm -rf __pycache__ dags/__pycache__
            git pull origin main
            docker compose build --no-cache
            docker compose up -d --remove-orphans
            docker system prune -af